version: '3.3'

services:
  db:
    image: postgres:14-alpine
    container_name: tree_menu_db
    restart: unless-stopped
    ports:
      - '5432:5432'
    volumes:
      - tree_menu_db:/var/lib/postgresql/data/
    env_file:
      - ./.env


volumes:
  tree_menu_db:
