# Generated by Django 4.1.5 on 2023-01-04 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='url',
        ),
    ]
