# Generated by Django 4.1.5 on 2023-01-04 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_alter_item_name'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='item',
            constraint=models.UniqueConstraint(fields=('slug', 'menu'), name='slug_menu_uniquetogether'),
        ),
    ]
