# Generated by Django 4.1.5 on 2023-01-04 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_item_slug_menu_uniquetogether'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='slug',
            field=models.SlugField(verbose_name='Слаг'),
        ),
    ]
