# Generated by Django 4.1.5 on 2023-01-04 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0007_alter_item_slug'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='item',
            name='slug_menu_uniquetogether',
        ),
        migrations.AlterField(
            model_name='item',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='Слаг'),
        ),
    ]
